### ISSUE TITLE
[BUG] The RPSLS Images are not arranged in the Pentagon shape

### ISSUE THREAD

**Issue by UsmanButt1** [UsmanButt1/script-spartans#11]
As per the wireframe design, the RPSLS images need to be arranged in a Pentagon shape.

The HTML and CSS coding needs to be looked at to resolve this issue. Maybe needs flexbox to resolve perhaps?

**Comment by scientistigwe** [comment]
Kindly Note, I tried putting the images in pentagon shape but I discovered its taking more vertical space which increases chances of scrolling up and down when playing game. Lets review this please.
